name: Preview deploy

on:
  push:
    branches:
      - main

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint

  get_ios_build:
    name: Check existing iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: preview

  build_ios:
    name: Build iOS
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: preview

  update_ios:
    name: Publish OTA update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      channel: preview
      platform: ios
